#!/bin/sh
cd ~
# user preferred settings

#cursor size
export XCURSOR_SIZE=24

# text editor
export MICRO_TRUECOLOR=1
export EDITOR=/usr/bin/nvim

#browser
export BROWSER=firedragon
#terminal
export TERM=foot
#mail
export MAIL=thunderbird

# check /usr/local/bin/hyprstart

# OWN CHANGES
export XDG_CURRENT_DESKTOP=Hyprland
#export XDG_SESSION_DESKTOP=Hyprland
